=== Arrrrrr/Mustafar/death-star.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT deathstar (name,summary,assets+)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT summary (#PCDATA)>
    <!ELEMENT assets (weapons+,sithlords+,admirals+)>
       <!ELEMENT weapons (weapon+)>
            <!ELEMENT weapon (#PCDATA)>
       <!ELEMENT sithlords (master,apprentice)>
            <!ELEMENT master (#PCDATA)>
            <!ELEMENT apprentice (#PCDATA)>
        <!ELEMENT admirals (admiral+)>
            <!ELEMENT admiral (#PCDATA)>

=== Arrrrrr/Mustafar/death-star.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deathstar SYSTEM "death-star.dtd">
<deathstar>
    <name>The Death Star</name>
    <summary>A powerful weapon that can destroy entire planets</summary>
    <assets>
        <weapons>
            <weapon>Super laser</weapon>
            <weapon>TIE fighters</weapon>
            <weapon>Light sabers</weapon>
            <weapon>Turbo lasers</weapon>
        </weapons>
        <sithlords>
            <master>Darth Sidious</master>
            <apprentice>Darth Vader</apprentice>
        </sithlords>
        <admirals>
            <admiral>Tarkin</admiral>
            <admiral>Motti</admiral>
            <admiral>Tagge</admiral>
        </admirals>
    </assets>
</deathstar>
